# SPDX-License-Identifier: Apache-2.0
# Copyright(c) 2019 Wind River Systems, Inc.

# Default values for Deployment Manager instances

replicaCount: 1

namespace: titanium-deployment-manager

nameOverride: ""

rbacProxy:
  enabled: true
  port: 8443
  image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
  logLevel: 10

manager:
  debugger:
    enabled: false
    wait: false
    port: 30000
  logLevel: 0
  image:
    repository: titanium/deployment-manager
    tag: latest
    pullPolicy: IfNotPresent
  configmap:
    reconcilers:
      system:
        certificate:
          httpsRequired: false
      host:
        bmc:
          httpsRequired: false

tolerations:
  - effect: NoSchedule
    key: services
    operator: Equal
    value: disabled
  - effect: NoExecute
    key: services
    operator: Equal
    value: disabled

resources: {}
# NOTE(alegacy): disabled until required.
#  limits:
#    cpu: 100m
#    memory: 30Mi
#  requests:
#    cpu: 100m
#    memory: 20Mi
