apiVersion: v1
entries:
  titanium-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-08-27T12:52:20.440581449-05:00"
    description: A Helm chart for the Deployment Manager
    digest: 9c8cebc69d9edb4055ca36b7bbf9e276c969e0e92a5c2fa1a03b067d10967e69
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: titanium-deployment-manager
    urls:
    - titanium-deployment-manager-0.2.0.tgz
    version: 0.2.0
generated: "2019-08-27T12:52:20.438363834-05:00"
