apiVersion: v1
entries:
  titanium-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-06-24T09:11:28.609534246-05:00"
    description: A Helm chart for the Deployment Manager
    digest: 6e250efb416a0bc69cda616ccab30b9ec52abce2045941d5f19ebab9c29c5a29
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: titanium-deployment-manager
    urls:
    - titanium-deployment-manager-0.2.0.tgz
    version: 0.2.0
generated: "2019-06-24T09:11:28.604768986-05:00"
