apiVersion: v1
entries:
  titanium-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-07-25T09:00:47.205168718-05:00"
    description: A Helm chart for the Deployment Manager
    digest: 0fb65381ba7d67082075bd73e765fa717f74434de81ce7c76d57b6dbe6f92fb9
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: titanium-deployment-manager
    urls:
    - titanium-deployment-manager-0.2.0.tgz
    version: 0.2.0
generated: "2019-07-25T09:00:47.202564561-05:00"
