apiVersion: v1
entries:
  wind-river-cloud-platform-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-10-29T10:03:37.071750302-05:00"
    description: A Helm chart for the Deployment Manager
    digest: 4252ff2e031af0a5b4797e226c3fcc6aedb4a1cc676aecc82103a1412474a947
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: wind-river-cloud-platform-deployment-manager
    urls:
    - wind-river-cloud-platform-deployment-manager-2.0.0.tgz
    version: 2.0.0
generated: "2019-10-29T10:03:37.06879681-05:00"
