apiVersion: v1
entries:
  wind-river-cloud-platform-deployment-manager:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2019-10-30T12:06:00.818041932-05:00"
    description: A Helm chart for the Deployment Manager
    digest: 48f038d99402f3ef25d9532fbf59159c1a8a4f9c6227ae49e80ffcdd8aae1bd6
    icon: https://www.windriver.com/resources/images/wr-logo-red-2018.png
    name: wind-river-cloud-platform-deployment-manager
    urls:
    - wind-river-cloud-platform-deployment-manager-1.0.0.tgz
    version: 1.0.0
generated: "2019-10-30T12:06:00.815838197-05:00"
