apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: {{ .Values.rbacProxy.port | quote }}
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: {{ include "helm.name" . }}-metrics-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.rbacProxy.port }}
    targetPort: https
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
